//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyChanger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxyChanger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen Icon Theme has been developed by The Oxygen Team.
        ///
        ///Art Directors:
        ///Nuno F. Pinheiro &lt;nuno@oxygen-icons.org&gt;
        ///David Vignoni &lt;david@oxygen-icons.org&gt;
        ///
        ///Naming Coordinator
        ///Jakob Petsovits &lt;jpetso@gmx.at&gt;
        ///
        ///Designers:
        ///David J. Miller &lt;miller@oxygen-icons.org&gt;
        ///David Vignoni &lt;david@oxygen-icons.org&gt;
        ///Johann Ollivier Lapeyre &lt;johann@oxygen-icons.org&gt;
        ///Kenneth Wimer &lt;ken@oxygen-icons.org&gt; 
        ///Nuno F. Pinheiro &lt;nuno@oxygen-icons.org&gt;
        ///Riccardo Iaconelli &lt;riccardo@oxygen-icons.org&gt;
        ///David J. Miller &lt;miller@oxygen-icons.o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandLine Arguments:
        ///===================
        ////enable  - Enable proxy setting
        ////disable - Disable proxy setting
        ///===================
        ///Example(s):
        ///	ProxyChanger.exe /disable
        ///	ProxyChanger.exe /enable 192.168.1.1:8080
        ///===================
        ///Example Local Address Bypass:
        ///	ProxyChanger.exe /enable 192.168.1.1:8080 /bypass
        ///=================== ===================
        ///Copyright © 2019 yasinvs 
        ///All Rights Reserved.
        /// </summary>
        internal static string CommandLine_Arguments {
            get {
                return ResourceManager.GetString("CommandLine_Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
